export const pageNames = {
  appointmentCategories: 'appointmentCategories',
  appointmentCategory: 'appointmentCategory',
  appointments: 'appointments',
  appointment: 'appointment',
  clinicianCategories: 'clinicianCategories',
  clinicianCategory: 'clinicianCategory',
  clinicians: 'clinicians',
  clinician: 'clinician',
  deviceCategories: 'deviceCategories',
  deviceCategory: 'deviceCategory',
  devices: 'devices',
  device: 'device',
  home: 'home',
  roles: 'roles',
  role: 'role',
  users: 'users',
  user: 'user',
  login: 'login',
  patients: 'patients',
  patient: 'patient',
  registration: 'registration',
  roomCategories: 'roomCategories',
  roomCategory: 'roomCategory',
  rooms: 'rooms',
  room: 'room',
} as const;

export type Page = (typeof pageNames)[keyof typeof pageNames];
